language: node_js
node_js:
  - '12'

cache: npm

script:
  - ./bin/run --version
  - ./bin/run --help
  - npm test
  - echo $testering

deploy:
  provider: npm
  email: $npm_email
  api_key: $npm_auth
  on:
    tags: true
